src/objects/cb5__CBAccount__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBAccountType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account Type</label>
        <referenceTo>cb5__CBAccountType__c</referenceTo>
        <relationshipLabel>CB Accounts</relationshipLabel>
        <relationshipName>CBAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBSubAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account Subtype</label>
        <referenceTo>cb5__CBSubAccount__c</referenceTo>
        <relationshipLabel>CB Accounts</relationshipLabel>
        <relationshipName>CB_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Account</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBAccountType__c.object
<CustomObject>
    <fields>
        <fullName>cb5__Sign__c</fullName>
        <label>Sign</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>+</fullName>
                </value>
                <value>
                    <fullName>-</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CB Account Type</label>
    <nameField>
        <label>CB Account Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Account Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBAmount__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBBudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Budget Line</label>
        <referenceTo>cb5__CBBudgetLine__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CBAmounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBBudgetYear__c</fullName>
        <formula>cb5__CBPeriod__r.cb5__CBBudgetYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB Budget Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>cb5__CBPeriod__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CB_Amounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Amount</label>
    <nameField>
        <label>CB Line Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBBudgetLine__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBAccountType__c</fullName>
        <formula>cb5__CBAccount__r.cb5__CBAccountType__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__CBAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>cb5__CBAccount__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBBudgetYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Budget Year</label>
        <referenceTo>cb5__CBBudgetYear__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CB_Budget_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBScenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Scenario</label>
        <referenceTo>cb5__CBScenario__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CB_Budget_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBVariable1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>cb5__CBVariable1__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Budget Line</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cb5__CBBudgetYear__c.object
<CustomObject>
    <fields>
        <fullName>cb5__End__c</fullName>
        <formula>ADDMONTHS(cb5__Start__c, 12) -  1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cb5__Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CB Budget Year</label>
    <nameField>
        <label>CB Budget Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBInvoice__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>cb5__CBAccount__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBBudgetYear__c</fullName>
        <formula>cb5__CBPeriod__r.cb5__CBBudgetYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB Budget Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__CBPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>cb5__CBPeriod__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBVariable1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>cb5__CBVariable1__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBOrgVariable__c.object
<CustomObject>
    <label>CB Org Variable</label>
    <nameField>
        <label>CB Org Variables Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Org Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBPeriod__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBBudgetYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Budget Year</label>
        <referenceTo>cb5__CBBudgetYear__c</referenceTo>
        <relationshipLabel>CB Periods</relationshipLabel>
        <relationshipName>CBPeriods</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cb5__Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBScenario__c.object
<CustomObject>
    <label>CB Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBSubAccount__c.object
<CustomObject>
    <label>CB Account Subtype</label>
    <nameField>
        <label>CBSubAccount__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Sub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBVariable1__c.object
<CustomObject>
    <label>CB Variable 1</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Fund</fullName>
        <active>true</active>
        <businessProcess>Funding</businessProcess>
        <description>CloudBudget Grant Management</description>
        <label>Fund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <businessProcess>Granting</businessProcess>
        <description>CloudBudget Grant Management</description>
        <label>Grant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBGMTest.cls
/** 
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

 */

@isTest
public with sharing class CBGMTest {

	@TestSetup
	public static void generateInitialData() {
		/*cb5__CBOrgVariable__c orgVariable = new cb5__CBOrgVariable__c();
		insert orgVariable;

		cb5__CBBudgetYear__c budgetYear = new cb5__CBBudgetYear__c(Name = '2024', cb5__Start__c = Date.newInstance(2024, 1, 1));
		insert budgetYear;

		List<cb5__CBPeriod__c> periods = new List<cb5__CBPeriod__c>();
		for (Integer i = 1; i <= 12; i++) {
			periods.add(new cb5__CBPeriod__c(Name = 'M' + i, cb5__Start__c = Date.newInstance(2024, i, 1), cb5__End__c = Date.newInstance(2024, i, 25), cb5__CBBudgetYear__c = budgetYear.Id));
		}
		insert periods;

		cb5__CBAccountType__c accType = new cb5__CBAccountType__c(Name = 'Expenses', cb5__Sign__c = '+');
		insert accType;

		cb5__CBSubAccount__c subAccType = new cb5__CBSubAccount__c(Name = 'Other');
		insert subAccType;

		List<cb5__CBAccount__c> accounts = new List<cb5__CBAccount__c>();
		accounts.add(new cb5__CBAccount__c(Name = CBGMConst.DEFAULT_FUNDING_ACCOUNT_NAME, cb5__CBAccountType__c = accType.Id, cb5__CBSubAccount__c = subAccType.Id));
		accounts.add(new cb5__CBAccount__c(Name = CBGMConst.DEFAULT_GRANT_ACCOUNT_NAME, cb5__CBAccountType__c = accType.Id, cb5__CBSubAccount__c = subAccType.Id));
		insert accounts;

		List<cb5__CBScenario__c> scenarios = new List<cb5__CBScenario__c>();
		scenarios.add(new cb5__CBScenario__c(Name = CBGMConst.COMMITTED_FUND_SCENARIO_NAME));
		scenarios.add(new cb5__CBScenario__c(Name = CBGMConst.DEFAULT_FUNDING_ACCOUNT_NAME));
		scenarios.add(new cb5__CBScenario__c(Name = CBGMConst.BALANCE_FUND_SCENARIO_NAME));
		scenarios.add(new cb5__CBScenario__c(Name = CBGMConst.GRANT_PLAN_SCENARIO_NAME));
		insert scenarios;*/
	}

	@isTest
	public static void testFundsAndGrants() {
		CBGMInitController.generateInitialData();

		cb5__CBBudgetYear__c budgetYear = [SELECT Id, Name FROM cb5__CBBudgetYear__c LIMIT 1][0];

		Id fundRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Fund').getRecordTypeId();
		Id grantRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Grant').getRecordTypeId();
		List<Opportunity> opps = new List<Opportunity>();
		Opportunity fund = new Opportunity(Name = 'Fund', RecordTypeId = fundRecordTypeId, CloseDate = Date.newInstance(2024, 5, 5), StageName = 'Value Proposition');
		opps.add(fund);
		Opportunity grant = new Opportunity(Name = 'Grant', RecordTypeId = grantRecordTypeId, CloseDate = Date.newInstance(2024, 5, 5), StageName = 'Program Monitoring');
		opps.add(grant);
		insert opps;

		CBGMFundPageController.getAnalyticsServer();
		CBGMFundPageController.generateFundBudgetLinesServer(fund.Id);
		List<cb5__CBBudgetLine__c> fundBudgetLines = CBGMFundPageController.getFundBudgetLinesServer(fund.Id);
		cb5__CBAmount__c amount = fundBudgetLines[0].cb5__CBAmounts__r[0];
		CBGMFundPageController.saveFundAmountServer(amount);


		String var1FundId = [SELECT Id FROM cb5__CBVariable1__c][0].Id;
		CBGMGrantPageController.addBudgetLineServer(grant.Id, budgetYear.Id);
		List<cb5__CBBudgetLine__c> grantBudgetLines = CBGMGrantPageController.getGrantBudgetLinesServer(grant.Id);
		grantBudgetLines[0].cb5__CBVariable1__c = var1FundId;
		update grantBudgetLines;
		CBGMGrantPageController.saveGrantBudgetLineServer(grantBudgetLines[0]);
		CBGMGrantPageController.getAnalyticsServer(grant.Id);

		CBGMFundPageController.updateOpportunityByTriggerServer(fund.Id);
		CBGMFundPageController.getAllocationGrantsServer(fund.Id);
		CBGMFundPageController.recalculateFundBalanceBudgetServer(fund.Id);

		CBGMLockBudgetAction.cg();
		CBGMUnlockBudgetAction.cg();

		//CBGMFundBalanceBatch ba = new CBGMFundBalanceBatch();
		//Id jobId = Database.executeBatch(ba, 5);

		insert new cb5__CBInvoice__c(Name = 'test', cb5__CBVariable1__c = var1FundId);

		CBGMFundBalanceProcess process = new CBGMFundBalanceProcess();
		process.runProcess(null, null);


	}


}