src/objects/cb5__CBAmount__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBBudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Budget Line</label>
        <referenceTo>cb5__CBBudgetLine__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CBAmounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>cb5__CBPeriod__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CB_Amounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CB Amount</label>
    <nameField>
        <label>CB Line Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBBudgetLine__c.object
<CustomObject>
    <fields>
        <fullName>cb5__CBScenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Scenario</label>
        <referenceTo>cb5__CBScenario__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CB_Budget_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBVariable1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>cb5__CBVariable1__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>cb5__Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CB Budget Line</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cb5__CBLog__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Warnings</relationshipLabel>
        <relationshipName>CBLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cb5__Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CB Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBPeriod__c.object
<CustomObject>
    <fields>
        <fullName>cb5__ExtId__c</fullName>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBScenario__c.object
<CustomObject>
    <label>CB Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cb5__CBVariable1__c.object
<CustomObject>
    <label>CB Variable 1</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Fund</fullName>
        <active>true</active>
        <businessProcess>Funding</businessProcess>
        <description>CloudBudget Grant Management</description>
        <label>Fund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <businessProcess>Granting</businessProcess>
        <description>CloudBudget Grant Management</description>
        <label>Grant</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBGMWarningsService.cls
/** 
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

 */


public with sharing class CBGMWarningsService {

	static List<cb5__CBLog__c> logsToInsert = new List<cb5__CBLog__c>();
	static Set<String> oppIds = new Set<String>();

	static Map<String, String> oppBalanceShortfallMap {
		get {
			if (oppBalanceShortfallMap == null) {
				oppBalanceShortfallMap = new Map<String, String>();
				for (cb5__CBAmount__c a : [
						SELECT Id, cb5__CBPeriod__r.Name, cb5__CBBudgetLine__r.cb5__CBVariable1__r.cb5__ExtId__c, cb5__Value__c
						FROM cb5__CBAmount__c
						WHERE cb5__Value__c < 0
						AND cb5__CBBudgetLine__r.cb5__CBScenario__r.Name = :CBGMConst.BALANCE_FUND_SCENARIO_NAME
						AND cb5__CBBudgetLine__r.cb5__CBVariable1__r.cb5__ExtId__c IN:oppIds
						ORDER BY cb5__CBPeriod__r.cb5__Start__c
				]) {
					String message = 'The budget shortfall in ' + a.cb5__CBPeriod__r.Name + ' is $' + (a.cb5__Value__c * -1);
					oppBalanceShortfallMap.put(a.cb5__CBBudgetLine__r.cb5__CBVariable1__r.cb5__ExtId__c, message);
				}
			}
			return oppBalanceShortfallMap;
		}
		set;
	}

	public static void updateWarnings(List<String> opportunityIds) {
		if (opportunityIds == null) {
			for (Opportunity opp : [SELECT Id FROM Opportunity WHERE RecordType.Name = 'Fund' OR RecordType.Name = 'Grant']) {
				oppIds.add(opp.Id);
			}
		} else {
			oppIds = new Set<String> (opportunityIds);
		}
		for (String oppId : oppIds) {
			populateShortfallOpportunityWarnings(oppId);
		}
		deleteOldLogs();
		insert logsToInsert;
	}

	private static void deleteOldLogs() {
		delete [SELECT Id FROM cb5__CBLog__c WHERE Opportunity__c IN:oppIds];
	}

	private static void populateShortfallOpportunityWarnings(String oppId) {
		String logMessage = oppBalanceShortfallMap.get(oppId);
		if (logMessage == null) return ;
		logsToInsert.add(new cb5__CBLog__c(cb5__Type__c = 'Warning', Opportunity__c = oppId, cb5__Description__c = logMessage));
	}

}